name: CWA CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    name: Lint and Test All Clients

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      - name: Run Tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    name: Build All Clients
    needs: lint-test

    strategy:
      matrix:
        client: [
            "clients/vercel_1/client_1",
            # Add additional clients here as needed
          ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Build Client
        working-directory: ${{ matrix.client }}
        run: npm run build
